# .travis.yml for R projects.
#
# https://travis-ci.org/lauriekell/diags

warnings_are_errors: false

os:
  - linux
  - osx

language: R

r:
  - release
  - devel
  
sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
